In [2]:
import numpy as np

In [3]:
a1 = np.array(['Spark', 'Hadoop', 'Python', 'R'])

In [4]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

In [14]:
a2 = np.array([['ALtura', 'Largura', 'Amplitude'], [48, 72, 10], [48, 72, 10]])

In [6]:
a2[1][2]

'10'

In [7]:
a3 = np.array([[10, 20, 30], [40, 50, 60]])

In [8]:
a3[0] * a3[1]

array([ 400, 1000, 1800])

In [15]:
#Tamanho dos arrays
print(a1.shape)
print(a2.shape)
print(a3.shape)

(4,)
(3, 3)
(2, 3)


In [19]:
#Dimensoes do array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
2


In [20]:
a3.max()

60

In [21]:
#Metodo arrange
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
array2 = np.arange(0,100, 10)
array2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
#Criando estrutura de dados com linspace, 20 elementos entre 0 e 10
matriz = np.linspace(0, 10, 20)
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
matriz = np.linspace(0, 10, 5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
#Estrutura de matrizes
matriz = np.zeros((10, 10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
#numpy.ones
matriz = np.ones((2, 3))
matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
matriz = np.eye(10)
matriz

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
matriz = np.diag((2, 4, 6, 8 , 10, 12, 14, 16, 18, 20))
matriz

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20]])

In [32]:
matriz = np.empty((10,5))
matriz

array([[0.00000000e+000, 4.67576779e-310, 0.00000000e+000,
        0.00000000e+000, 4.94065646e-324],
       [0.00000000e+000, 7.08746594e-312, 0.00000000e+000,
        5.94158822e-313, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 4.67576623e-310, 6.90383788e-310,
        4.67576624e-310

In [33]:
matriz = np.tile(([1,2], [3,4], [5,6]),3)
matriz

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [35]:
matriz = np.tile(([1,2], [3,4], [5,6]),(3,6)) #Numero de vezes do array na vertical, numero de vezes do array na horizontal
matriz

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])