In [2]:
#Importação numpy
import numpy as np

In [5]:
#podemos passar um tipo para o array por parametro
a = np.array([-10, 10, 20, 30], dtype = 'float')

In [6]:
a

array([-10.,  10.,  20.,  30.])

In [8]:
#A peopriedade dtype me retorna o tipo dos elementos do array
a.dtype

dtype('float64')

In [10]:
#Caso não passar o tipo para o python, será passado automaticamente.
b = np.array([-10, 10, 20, 30])
b.dtype

dtype('int64')

In [11]:
# Caso haja tipos diferentes, python irá considerar o elemnto mais especifico.
c = np.array([10, 20, 30, 40.5])
c.dtype

dtype('float64')

In [12]:
d = np.array(['Universidade', 'dos', 'dados'])

In [13]:
d.dtype

dtype('<U12')

In [15]:
e = np.array([True, False, False, True])

In [16]:
e.dtype

dtype('bool')

In [ ]:
#CAST DE ARRAYS 

In [3]:
f = np.array([-9, 10, 20.7])
f.dtype

dtype('float64')

In [4]:
#conversão papra o tipo inteiro.
f.astype(int)

array([-9, 10, 20])

In [5]:
#CRIANDO ARRRAY COM OPERAÇÕES ARITIMÉTICAS.
#FUNÇÃO ARANGE SERVE PARA CRIAR UM ARRAY
array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [9]:
#Podemos criar um array com qualquer operação aritmética
#Potência 2
array = np.arange(10) ** 2
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
#OPERAÇÕES ARITMÉTICAS COM ARRAYS.
arrayA = np.arange(0, 10)
arrayB  = np.arange(0, 10) + 1

In [15]:
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
#Soma

arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
#Subtração
arrayA - arrayB

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [20]:
#Divisão 
arrayA / arrayB

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [21]:
#Comparação de  arrays
arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [23]:
#ULTILIZANDO A TABELA VERADE
array1 = np.array([True, False, True, False])
array2 = np.array([False, False, True, False])
np.logical_or(array1, array2)



array([ True, False,  True, False])

In [24]:
array1 = np.array([True, False, True, False])
array2 = np.array([False, False, True, False])
np.logical_and(array1, array2)

array([False, False,  True, False])

In [31]:

A = np.array([2, 4, 6])
B = np.array([2, 2, 2])

In [32]:
#Produto das matrizes
A * B


array([ 4,  8, 12])

In [33]:
print(np.dot(A, B))

24


In [34]:
A = np.array([3, 7, 10])
B = np.array([9, 3, 2])

In [35]:
print(np.dot(A, B))

68


In [38]:
#CÓPIA DE ARRAYS
A = np.arange(10)

In [39]:
B = A[5:]

In [42]:
B

array([5, 6, 7, 8, 9])

In [43]:
A[:] = 0

In [46]:
B

array([0, 0, 0, 0, 0])

In [51]:
A = np.arange(10)

In [52]:
B = A[:5].copy()

In [53]:
B

array([0, 1, 2, 3, 4])

In [54]:
A[:] = 0
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
B

array([0, 1, 2, 3, 4])