In [1]:
import numpy as np

In [2]:
a = [1, 2, 11, 6, 8, 18, 2]

array = np.array(a)
print(type(array))

<class 'numpy.ndarray'>


In [3]:
#Verificando o tamanho dos arrays
print(array.shape)

(7,)


In [4]:
#primemiro elemento
array[0]

1

In [6]:
#Indice 1 até o 5
print(array[1:5])

[ 2 11  6  8]


In [7]:
#Trazendo de 2 em 2 
print(array[1:5:2])

[2 6]


In [8]:
#trazendo com índices negativos
#-7 representa o primeiro elemento da esquerda, -3 o ultimo elemento a ser trazido
print(array[-7:-3])

[ 1  2 11  6]


In [9]:
#índice 3 até o fim
print(array[3:])

[ 6  8 18  2]


In [10]:
#Início até o índice 4
print(a[:4])

[1, 2, 11, 6]


In [11]:
#Indice 3 até ofim
print(a[3:])

[6, 8, 18, 2]


In [13]:
#invertendo o array
print(a[::-1])

[2, 18, 8, 6, 11, 2, 1]


In [14]:
#Concatenando dois arrays
x = np.array([2, 6, 8, 4])
y = np.array([11, 8, 2])

z = np.concatenate([x, y])
print(z)

[ 2  6  8  4 11  8  2]
