In [4]:
import numpy as np

In [5]:
A = [[1, 2, 3, 4], [5, 6, 7, 8], [10, 20, 30, 40], [50, 60, 70, 82]]
array = np.array(A)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 82]]


In [6]:
#Linha de Indice 2
print(array[2])

[10 20 30 40]


In [7]:
#Primeira linhha ultima coluna
print(array[0, -1])

4


In [8]:
#Atribuindo valor a uma posição da matriz
array[0, 0] = 0
print(array)

[[ 0  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 82]]


In [11]:
#TRABALHANDO COM INTERVALOS
#Pegando os numeros centrais
print(array[1:3, 1:3])

[[ 6  7]
 [20 30]]


In [12]:
# Pegando o intervalo 7, 8, 30 e 44
print(array[1:3, 2:4])

[[ 7  8]
 [30 40]]


In [13]:
# Trazendo somente a ultima coluna
print(array[:, -1])

[ 4  8 40 82]


In [14]:
#Trazendo somente a última linha
print(array[-1, :])

[50 60 70 82]


In [20]:
#Concatenando arrays multidimensionais
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6]])

C = np.concatenate((A, B))
print(C)

[[1 2]
 [3 4]
 [5 6]]
