In [5]:
import numpy as np

In [11]:
A = np.matrix([[1, 2], [3, 4]])
B = np.matrix([[5, 3], [8, 7]])

Z = np.array([
              [[2, 6], [8, 4]],
              [[2, 6], [8, 4]],
              [[2, 6], [8, 4]]
])

Y = np.array([2, 6, 8, 4])

In [14]:
Z = np.array([
              [[2, 6], [8, 4]],
              [[2, 6], [8, 4]],
              [[2, 6], [8, 4]]
])

In [16]:
print(type(A))
print(type(B))
print(type(Z))
print(type(Y))

<class 'numpy.matrixlib.defmatrix.matrix'>
<class 'numpy.matrixlib.defmatrix.matrix'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
print(Z.shape)
print(A.shape)
print(B.shape)
print(Y.shape)

(3, 2, 2)
(2, 2)
(2, 2)
(4,)


In [26]:
#Operações

print(A + B)
print("\n", Z * Z)

[[ 6  5]
 [11 11]]

 [[[ 4 36]
  [64 16]]

 [[ 4 36]
  [64 16]]

 [[ 4 36]
  [64 16]]]


In [27]:
#Multiplicação de índice * índice
print(np.multiply(Z, Z))

[[[ 4 36]
  [64 16]]

 [[ 4 36]
  [64 16]]

 [[ 4 36]
  [64 16]]]


In [28]:
#Inversa
print(np.linalg.inv(Z))

[[[-0.1   0.15]
  [ 0.2  -0.05]]

 [[-0.1   0.15]
  [ 0.2  -0.05]]

 [[-0.1   0.15]
  [ 0.2  -0.05]]]


In [29]:
from numpy.linalg import inv

In [31]:
print(inv(Z))

[[[-0.1   0.15]
  [ 0.2  -0.05]]

 [[-0.1   0.15]
  [ 0.2  -0.05]]

 [[-0.1   0.15]
  [ 0.2  -0.05]]]


In [32]:
#Transposta
print(Z.T)

[[[2 2 2]
  [8 8 8]]

 [[6 6 6]
  [4 4 4]]]
