In [1]:
import numpy as np

In [2]:
A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [3]:
A

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [4]:
A.T

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [5]:
np.transpose(A)

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [6]:
#Broadcasting
B = np.array([[100, 200, 300]])

In [7]:
B.T

array([[100],
       [200],
       [300]])

In [8]:
B.T + B

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

In [11]:
#Convertendo Matrizes em Arrays
A = np.array([np.arange(10, 50, 10), np.arange(100, 150, 10)])

In [12]:
A

array([array([10, 20, 30, 40]), array([100, 110, 120, 130, 140])],
      dtype=object)

In [13]:
A.shape

(2,)

In [14]:
A.ravel

<function ndarray.ravel>

In [15]:
#Convertendo Matrizes em Arrays
A = np.array([np.arange(10, 60, 10), np.arange(100, 150, 10)])

In [16]:
A

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [17]:
A.shape

(2, 5)

In [18]:
A.ravel()

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [19]:
A.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

In [20]:
#Operadores Lógicos
array = np.random.randint(1, 10, size = (4, 4))

In [21]:
array

array([[7, 9, 3, 8],
       [1, 6, 6, 3],
       [7, 6, 5, 4],
       [7, 1, 8, 7]])

In [22]:
np.any((array % 7) == 0)

True

In [23]:
np.all(array < 9)

False

In [24]:
#Reshaping
array = np.arange(1, 16)

In [25]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
array.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
#Ordenando Array
array = np.array([[3, 2], [10,  -1]])

In [31]:
array

array([[ 3,  2],
       [10, -1]])

In [32]:
array = np.array([[3, 2], [10, -1]])

In [33]:
array

array([[ 3,  2],
       [10, -1]])

In [34]:
#Ordenando por coluna
array.sort(axis = 0)

In [35]:
array

array([[ 3, -1],
       [10,  2]])

In [36]:
#Ordenando por linhas
array.sort(axis = -1)

In [37]:
array

array([[-1,  3],
       [ 2, 10]])